// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwniplbizfyfzvdsjvih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bmlwbGJpemZ5Znp2ZHNqdmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzY0MTQsImV4cCI6MjA3MDQxMjQxNH0.cFY6IU_Hn1akmNaGdBG0Dd_khnAL-PH8fSOHibnfwxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});